version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout      
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: build @lib-publish-version/a
          command: npm run build -- --prod @lib-publish-version/a
      - run:
          name: build @lib-publish-version/b
          command: npm run build -- --prod @lib-publish-version/b
      - run:
          name: release
          command: npm run semantic-release
